app/backend/__init__.py
__author__ = 'justus'
__date__ = ''

app/backend/views.py
from app import db
from os import walk
from app.models import User, Feed, Category, Country, Language
from flask import Blueprint, render_template, g, request, redirect, url_for, flash, session
from app.db_connect import DBConnect as DBc


node = Blueprint('backend', __name__, url_prefix='/backend')


@node.before_request
def before_request():
    g.db = DBc.db_connect()
    g.config = DBc().con_config()
    g.user = None

    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

    g.theme_list = []
    for root, dir_name, file_name in walk('./app/static/bootswatch'):
        g.theme_list.append(dir_name)


@node.teardown_request
def teardown_request(exception):
    db = getattr(g, 'db', None)
    if db is not None:
        db.close()


@node.route('/logout/')
def logout():
    session.pop('user_id', None)
    return redirect(url_for('index'))


@node.route('/')
def backend():
    page = 'backend/news_config.html'
    url = []
    all_feeds = Feed.query.all()
    feeds = Feed.query.join(User.urls).filter(User.id == g.user.id).all()
    for feed in feeds:
        url.append(feed)
    error = None
    return render_template('backend/config.html', feeds=url, all_feeds=all_feeds, error=error, page=page)


@node.route('/user-config/', methods=['GET', 'POST'])
def user_config():
    page = 'backend/user_config.html'
    users = User.query.all()

    if request.method == 'POST':
        if 'Delete' in request.form:
            user = User.query.filter_by(id=request.form['Delete']).first()
            db.session.delete(user)
            db.session.commit()
            flash("the user account is deleted!")
            return render_template('backend/config.html', page=page, users=users)
    return render_template('backend/config.html', page=page, users=users)


"""Form handlers"""


@node.route('/profile/', methods=["GET", "POST"])
def profile():
    page = 'backend/profile.html'
    # change user name and email, password not yet.
    # todo add change password and reset password option.
    if request.method == "POST":
        name = User.query.filter_by(id=g.user.id).first()
        name.nickname = request.form['Alias']
        name.email = request.form['Email']
        db.session.add(name)
        db.session.commit()
        flash("Your info has been updated!")

    # option for user to delete the account
    if 'Delete' in request.form:
        print request.form['Delete'], 'it is in here'
        remove = User.query.filter_by(id=g.user.id).first()
        db.session.delete(remove)
        db.session.commit()
        session.pop('user_id', None)
        return redirect(url_for('index'))
    return render_template('backend/config.html', page=page)


@node.route('/news-config/', methods=['GET', 'POST'])
def news_config():

    error = None
    if request.method == 'POST':
        print request.form
        try:
            if request.form['rssurl'] is None or '' and request.form['name'] is None or '':
                error = "you didn't fill in all the fields: "
            else:
                link = Feed(name=request.form['name'], url=request.form['rssurl'], category=request.form['category'],
                            country=request.form['country'], language=request.form['language'])
                db.session.add(link)
                db.session.commit()

        except BaseException as e:
            print "That didn't go as planned! ", e
            error = "You didn't fill in all the fields or maybe a double entry:"
        return redirect(url_for('backend.feed_config'))

    return redirect(url_for('backend.backend'))


@node.route('/select-feed/', methods=['GET', 'POST'])
def select_feed():
    if request.method == 'POST':
        user = User.query.filter_by(id=g.user.id).first()
        for id in request.form.itervalues():

            feed = Feed.query.filter_by(id=id).first()
            user.urls.append(feed)
            db.session.commit()

            flash('RSS feed [ %s ] has been added to your list.' % feed.name)

    return redirect(url_for('backend.news_config'))


@node.route('/delete-feed/', methods=['GET', 'POST'])
def delete_feed():
    if request.method == 'POST':
        if 'delete' in request.values:
            user = User.query.filter_by(id=g.user.id).first()
            feed = Feed.query.filter_by(id=request.form['delete']).first()
            user.urls.remove(feed)
            db.session.commit()

            flash('rss feed has been deleted')
            return redirect(url_for('backend.news_config'))
    return redirect(url_for('backend.news_config'))


# todo change the database on these methods
@node.route('/set-template/', methods=['GET', 'POST'])
def set_template():
    if request.method == 'POST':
        theme = request.form['btn_theme']
        g.db.execute('UPDATE config SET system_theme =?', (theme,))
        g.db.commit()
    return redirect(url_for('backend.news_config'))


@node.route('/site-config/', methods=['GET', 'POST'])
def site_config():
    page = 'backend/site_config.html'
    if request.method == 'POST':
        data = [(request.form['site_name']), (request.form['slogan'])]
        g.db.execute('UPDATE config SET name_website = ?, slogan = ?', data)
        g.db.commit()
    return render_template('backend/config.html', page=page)


@node.route('/feed-config/', methods=['GET', 'POST'])
def feed_config():
    page = 'backend/feed_config.html'
    all_feeds = Feed.query.all()
    category = Category.query.all()
    country = Country.query.all()
    language = Language.query.all()

    if request.method == 'POST':
        if 'Delete' in request.form:
            feed = Feed.query.filter_by(id=request.form['Delete']).first()
            db.session.delete(feed)
            db.session.commit()
            flash("the feed has been deleted!")
            return redirect(url_for('backend.feed_config'))
    return render_template('backend/config.html', page=page, all_feeds=all_feeds, category=category, country=country,
                           language=language)

app/templates/backend/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% for theme in g.config %}
        <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" id="bootstrap" href="/bootswatch/{{ theme.theme }}/bootstrap.min.css"/>
    {% endfor %}
    <title>{% block title %}{% endblock %}</title>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', {{ g.google_id }}, 'auto');
  ga('send', 'pageview');

</script>
</head>
<body>
{% include "backend/header.html" ignore missing %}

{% block content %}{% endblock %}

{% include 'backend/footer.html' ignore missing %}

{% block scripts %}{% endblock %}
</body>
</html>

app/templates/backend/config.html
{% extends "backend/base.html" %}
{% block title %}Configuration platform{% endblock %}

{% block content %}

    <div class="container">
        <hr>
        <div class="page-header">
            {% include 'backend/menu.html' ignore missing %}
        </div>
    <div class="">
        {% include page ignore missing %}
    </div>
    </div>
{% endblock %}

app/templates/backend/feed_config.html
<div class="well">
    <h2>Feed Configuration</h2>
</div>

{% for message in get_flashed_messages() %}
    <div class="bs-component">
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p>{{ message }}</p>
        </div>
    </div>
{% endfor %}

<div class="row">
    <div class="col-lg-12">
        <form method="post" action="/backend/news-config/">
            <div class="form-group">
                <span class="glyphicon glyphicon-asterisk" style="color:red"></span>
                <label for="rssurl">insert a new rss feed</label>
                <input type="url" required="required" class="form-control" name="rssurl"
                       placeholder="rss feed" value="{{ request.form.rssurl }}">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-asterisk" style="color:red"></span>
                <label for="name">Name of rss feed</label>
                <input type="text" required="required" class="form-control" name="name"
                       placeholder="Name"
                       value="{{ request.form.name }}">
            </div>
            <div class="row">
                <div class="col-md-3 col-lg-4">
                    <div class="form-group">
                        <label for="edition">additional feed edition / category</label>
                        <select class="form-control" name="category">
                            <option value="">Select</option>
                            {% for category in category %}
                                <option value="{{ category.id }}">{{ category.name|safe }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-4">
                    <div class="form-group">
                        <label for="country">Country</label>
                        <select class="form-control" name="country">
                            <option value="">Select</option>
                            {% for country in country %}
                                <option value="{{ country.id }}">{{ country.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-3 col-lg-4">
                    <div class="form-group">
                        <label for="language">Language</label>
                        <select class="form-control" name="language">
                            <option value="">Select</option>
                            {% for language in language %}
                                <option value="{{ language.id }}">{{ language.language }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" name="btn1" class="btn btn-default">Submit</button>
            </div>

        </form>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-condensed table-striped table-responsive">
            <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>category</td>
                <td>Country</td>
                <td>Language</td>
                <td>url</td>
            </tr>
            </thead>
            <form class="form-horizontal" method="POST" action=".">
                {% for feeds in all_feeds %}
                    <tr>
                        <td>{{ feeds.id }}</td>
                        <td>{{ feeds.name }}</td>
                        <td>{{ feeds.cat.name }}</td>
                        <td>{{ feeds.count.name }}</td>
                        <td>{{ feeds.lang.language }}</td>
                        <td><a href="{{ feeds.url }}" target="_blank">{{ feeds.url }}</a></td>
                        <td>
                            <button class="btn btn-sm btn-default" value="{{ feeds.id }}" id="=delete" name="Delete">
                                Delete
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </form>
        </table>
    </div>
</div>

app/templates/backend/footer.html
{% block content %}

    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <script>
        $("#theme_list li").click(function () {
            var theme_drop_down_selected = $('#theme_list li').attr('id');
            var dirLocator = "/bootswatch/"
            theme_drop_down_selected = $(this).attr('id');
            var themeDropDownSelected = dirLocator.concat(theme_drop_down_selected, '/bootstrap.min.css')
            $('#bootstrap').attr('href', themeDropDownSelected);
        });
    </script>
    <script>
        $("#theme_list li").click(function () {
            var theme_drop_down_selected2 = $('#theme_list li').attr('id');
            theme_drop_down_selected2 = $(this).attr('id');
            $('#btn_theme').attr('value', theme_drop_down_selected2);
            $('myForm').append("<input type='hidden' name='submitValue' value='" + theme_drop_down_selected2 + "' />");
            $('#myForm').trigger('select');
        });
    </script>
{% endblock %}

app/templates/backend/header.html
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            {% for config in g.config %}
                <a href="{{ url_for('index') }}" class="navbar-brand">{{ config.title }}</a>
            {% endfor %}
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse pull-right" id="navbar-main">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span
                            class="caret"></span></a>
                    <ul id="theme_list" class="dropdown-menu" aria-labelledby="themes">
                        {% for theme in g.theme_list[0] %}
                            <li id="{{ theme }}"><a href="#">{{ theme }}</a></li>
                        {% endfor %}
                    </ul>
                </li>

                {% if "user_id" in session %}
                    <li>
                        <a href="{{ url_for('backend.backend') }}">Config</a>
                    </li>
                    <li>
                        <a href="{{ url_for('backend.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="#" data-toggle="modal" data-target="#myModal">Login</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</div>

app/templates/backend/menu.html
<ul class="nav nav-tabs">
                <li class=""><a aria-expanded="true" href="{{ url_for('.backend') }}">News</a></li>
                <li class=""><a aria-expanded="true" href="{{ url_for('backend.profile') }}">Profile</a></li>
                {% if g.user.role == 0 %}
                    <li class=""><a aria-expanded="false" href="{{ url_for('backend.site_config') }}">Site Config</a></li>
                    <li class=""><a aria-expanded="false" href="{{ url_for('backend.feed_config') }}">Feed Config</a></li>
                    <li class=""><a aria-expanded="false" href="{{ url_for('backend.user_config') }}">User Config</a></li>
                {% endif %}
            </ul>

app/templates/backend/news_config.html
<div class="well">
    <h2>News Configuration</h2>
</div>

{% for message in get_flashed_messages() %}
    <div class="bs-component">
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p>{{ message }}</p>
        </div>
    </div>
{% endfor %}

<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-12">
                <div>
                    <span class="text-center"><h3>available news feeds.</h3></span>

                    <form name="feedForm" class="form-group" method="post" action="select-feed/">
                        <div class="form-group">
                            {% for feed in all_feeds %}
                                {% if feed.url in feeds|string %}
                                {% else %}
                                    <button class="btn btn-warning" style="border: 1px solid #ffffff; width: 100%;
                                    " value="{{ feed.id }}" name="{{ feed.id }}">{{ feed.name }}</button>
                                {% endif %}
                            {% endfor %}
                            {% if feeds == all_feeds %}
                                <h4 class="text-center">No more available feeds</h4>
                            {% endif %}
                        </div>

                    </form>
                </div>
            </div>
        </div>

        {% if error %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endif %}
    </div>


    <div class="col-lg-6">
        <span class="text-center"><h3>Your subcribed news feeds</h3></span>
        {% for url in feeds %}
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="delete-feed/">
                        <button type="submit" class="btn btn-primary" style="width: 100%;
                                border: 1px solid #ffffff;" name="delete" id="delete"
                                value="{{ url.id }}">
                            {{ url.name }}
                        </button>
                    </form>
                </div>

            </div>
        {% endfor %}
    </div>
</div>

app/templates/backend/profile.html
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h3>This is the profile page</h3>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-12">
            <p>

            <h3>Hello
                <small> {{ g.user.nickname }}</small>
            </h3>
            here you can change some details</p>

            <form class="form-horizontal" method="POST" action=".">
                <div class="form-group">
                    <label class="col-lg-2 control-label" for="Alias">User name</label>

                    <div class="col-lg-6">
                        <input type="text" class="form-control" value="{{ g.user.nickname }}" placeholder="Your name here" name="Alias">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label" for="Email">Email</label>

                    <div class="col-lg-6">
                        <input type="email" class="form-control" value="{{ g.user.email }}" placeholder="Email address" name="Email">
                    </div>
                </div>
                <input type="submit" class="btn btn-success" value="submit">

                <hr>
        <p>if you want you can delete your account here.</p>
                <input type="submit" class="btn btn-danger" id="Delete" name="Delete" value="delete account">
                <span class="help-block">Warning this can't be undone.</span>
            </form>
            <br>

            <p>{% if g.user.status == 1 %}
                Your account hasn't been confirmed yet.
            {% elif g.user.status == 2 %}
                Your account is activated
            {% else %}
                Your account is disabled
            {% endif %}</p>
        </div>
    </div>
{% endblock %}

app/templates/backend/site_config.html
<div class="well">
    <h2>Site Configuration</h2>
</div>
<div class="row">
    <div class="col-sm-6">
        <form method="post" action="site-config/">
            <div class="form-group">
                <label for="site_name">name your rss feed channel</label>
                <input type="text" required="required" class="form-control" name="site_name"
                       placeholder="Site name" value="{{ request.form.site_name }}">
            </div>
            <div class="form-group">
                <label for="slogan">Nice slogan for your website</label>
                <input type="text" required="required" class="form-control" name="slogan"
                       placeholder="Slogan"
                       value="{{ request.form.slogan }}">
            </div>
            <br>
            <button type="submit" name="main" class="btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-sm-6">
        <div>
            <form id="myForm" method="post" action="set-template/">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span
                            class="caret"></span></a>
                    <ul id="theme_list" class="dropdown-menu" aria-labelledby="themes">
                        {% for theme in g.theme_list[0] %}
                            <li id="{{ theme }}"><a href="#">{{ theme }}</a></li>
                        {% endfor %}
                    </ul>
                    <p>Set here system wide theme.</p>
                </li>
                <button type="submit" id="btn_theme" name="btn_theme" class="btn btn-default" value="">Submit</button>
            </form>
        </div>
    </div>
</div>

app/templates/backend/user_config.html
<div class="well">
    <h2>Users Configuration</h2>
</div>

{% for message in get_flashed_messages() %}
    <div class="bs-component">
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p>{{ message }}</p>
        </div>
    </div>
{% endfor %}
<div class="row">
    <div class="col-md-6">
        <a href="#">add account</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        {% for users in users %}
            <div class="panel panel-group">
                <div class="panel-heading">
                    {{ users.nickname }}
                </div>
                <div class="panel-body">
                    <table class="table table-condensed table-striped">
                        <tr>
                            <td>users id:</td>
                            <td>{{ users.id }}</td>
                        </tr>
                        <tr>
                            <td>users email:</td>
                            <td>{{ users.email }}</td>
                        </tr>
                        <tr>
                            <td>users role:</td>
                            <td>{{ users.role }}</td>
                        </tr>
                        <tr>
                            <td>users status:</td>
                            <td>{{ users.status }}</td>
                        </tr>
                        <tr>
                            <td>users url:</td>
                            <td>{{ users.url }}</td>
                        </tr>
                        <tr>
                            <td>user signup date:</td>
                            {% if users.signup_date == None %}
                                <td><p>Not specified</p></td>
                            {% else %}
                            <td>{{ users.signup_date.strftime('%d %b %Y %H:%M') }}</td>
                            {% endif %}
                        </tr>
                    </table>
                    {% if users.role == 0 %}
                        <p style="color: #8b0000">Can't delete this account</p>
                    {% else %}
                        <form class="form-horizontal" method="POST" action=".">
                            <button class="btn btn-alarm" id="Delete" value="{{ users.id }}" name="Delete">Delete
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

</div>